-- ============================================================
-- DRITO
-- PASO 15A.2
-- BASE DE AUDITORÍA OPERACIONAL
--
-- Objetivo:
-- - mantener separada la auditoría de usuarios/permisos;
-- - registrar operaciones sensibles de los módulos de Drito;
-- - preservar aislamiento por comercio_id;
-- - impedir escritura directa desde frontend;
-- - habilitar consulta únicamente mediante permiso auditoria.ver.
--
-- Esta migración NO conecta todavía Ventas, Compras, Caja,
-- Stock ni otros módulos. Crea solamente la infraestructura.
-- ============================================================


-- ============================================================
-- 0. PRECONDICIONES
-- ============================================================

do $$
begin

  if to_regclass('public.comercios') is null then
    raise exception
      'Falta public.comercios';
  end if;

  if to_regclass('public.permisos_sistema') is null then
    raise exception
      'Falta public.permisos_sistema';
  end if;

  if to_regclass('public.roles_permisos') is null then
    raise exception
      'Falta public.roles_permisos';
  end if;

  if to_regprocedure(
    'public.exigir_permiso_comercio(uuid,text)'
  ) is null then
    raise exception
      'Falta public.exigir_permiso_comercio(uuid,text)';
  end if;

end;
$$;


-- ============================================================
-- 1. PERMISO ESPECÍFICO
-- ============================================================

insert into public.permisos_sistema (
  codigo,
  modulo,
  accion,
  nombre,
  descripcion,
  sensible,
  orden,
  activo
)
values (
  'auditoria.ver',
  'auditoria',
  'ver',
  'Ver auditoría',
  'Consultar el historial de operaciones sensibles realizadas dentro del comercio.',
  true,
  1300,
  true
)
on conflict (codigo) do update
set
  modulo = excluded.modulo,
  accion = excluded.accion,
  nombre = excluded.nombre,
  descripcion = excluded.descripcion,
  sensible = excluded.sensible,
  orden = excluded.orden,
  activo = true,
  updated_at = now();


-- Por defecto únicamente el administrador puede consultar
-- el historial operacional completo.

insert into public.roles_permisos (
  rol,
  permiso_codigo,
  permitido
)
values (
  'admin',
  'auditoria.ver',
  true
)
on conflict (rol, permiso_codigo) do update
set
  permitido = true;


-- ============================================================
-- 2. TABLA DE AUDITORÍA OPERACIONAL
-- ============================================================

create table if not exists
public.auditoria_operaciones (
  id bigint
    generated by default as identity
    primary key,

  comercio_id uuid not null
    references public.comercios(id)
    on delete restrict,

  modulo text not null,

  accion text not null,

  entidad_tipo text not null,

  entidad_id text,

  referencia text,

  detalle jsonb not null
    default '{}'::jsonb,

  realizado_por uuid
    references auth.users(id)
    on delete set null,

  created_at timestamptz not null
    default now(),

  constraint auditoria_operaciones_modulo_no_vacio
    check (length(trim(modulo)) > 0),

  constraint auditoria_operaciones_accion_no_vacia
    check (length(trim(accion)) > 0),

  constraint auditoria_operaciones_entidad_no_vacia
    check (length(trim(entidad_tipo)) > 0),

  constraint auditoria_operaciones_detalle_objeto
    check (jsonb_typeof(detalle) = 'object')
);


-- ============================================================
-- 3. ÍNDICES
-- ============================================================

create index if not exists
auditoria_operaciones_comercio_fecha_idx
on public.auditoria_operaciones (
  comercio_id,
  created_at desc
);


create index if not exists
auditoria_operaciones_comercio_modulo_fecha_idx
on public.auditoria_operaciones (
  comercio_id,
  modulo,
  created_at desc
);


create index if not exists
auditoria_operaciones_entidad_idx
on public.auditoria_operaciones (
  comercio_id,
  entidad_tipo,
  entidad_id
);


-- ============================================================
-- 4. SEGURIDAD DE TABLA
-- ============================================================

alter table public.auditoria_operaciones
  enable row level security;


-- No se habilita ninguna policy de escritura directa.
-- Las altas se realizarán exclusivamente mediante el helper
-- interno definido más abajo.

revoke all on table
public.auditoria_operaciones
from anon, authenticated;


-- Tampoco concedemos SELECT directo.
-- La lectura se realizará mediante una RPC protegida
-- por auditoria.ver.


-- ============================================================
-- 5. HELPER INTERNO DE REGISTRO
-- ============================================================

create or replace function
public.__drito_registrar_auditoria_operacion(
  p_comercio_id uuid,
  p_modulo text,
  p_accion text,
  p_entidad_tipo text,
  p_entidad_id text default null,
  p_referencia text default null,
  p_detalle jsonb default '{}'::jsonb,
  p_realizado_por uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_id bigint;

  v_modulo text;
  v_accion text;
  v_entidad_tipo text;

  v_actor uuid;
begin

  if p_comercio_id is null then
    raise exception
      'El comercio es obligatorio para registrar auditoría';
  end if;


  if not exists (
    select 1
    from public.comercios c
    where c.id = p_comercio_id
  ) then
    raise exception
      'El comercio indicado no existe';
  end if;


  v_modulo :=
    nullif(trim(coalesce(p_modulo, '')), '');

  v_accion :=
    nullif(trim(coalesce(p_accion, '')), '');

  v_entidad_tipo :=
    nullif(trim(coalesce(p_entidad_tipo, '')), '');


  if v_modulo is null then
    raise exception
      'El módulo de auditoría es obligatorio';
  end if;


  if v_accion is null then
    raise exception
      'La acción de auditoría es obligatoria';
  end if;


  if v_entidad_tipo is null then
    raise exception
      'El tipo de entidad auditada es obligatorio';
  end if;


  if p_detalle is not null
     and jsonb_typeof(p_detalle) <> 'object' then
    raise exception
      'El detalle de auditoría debe ser un objeto JSON';
  end if;


  v_actor :=
    coalesce(
      p_realizado_por,
      auth.uid()
    );


  insert into public.auditoria_operaciones (
    comercio_id,
    modulo,
    accion,
    entidad_tipo,
    entidad_id,
    referencia,
    detalle,
    realizado_por
  )
  values (
    p_comercio_id,
    v_modulo,
    v_accion,
    v_entidad_tipo,
    nullif(trim(coalesce(p_entidad_id, '')), ''),
    nullif(trim(coalesce(p_referencia, '')), ''),
    coalesce(p_detalle, '{}'::jsonb),
    v_actor
  )
  returning id
  into v_id;


  return v_id;

end;
$function$;


-- Helper exclusivamente interno.
-- El frontend no puede invocarlo directamente.

revoke all on function
public.__drito_registrar_auditoria_operacion(
  uuid,
  text,
  text,
  text,
  text,
  text,
  jsonb,
  uuid
)
from public, anon, authenticated;


-- ============================================================
-- 6. RPC DE CONSULTA
-- ============================================================

create or replace function
public.obtener_auditoria_operaciones(
  p_comercio_id uuid,
  p_fecha_desde date default null,
  p_fecha_hasta date default null,
  p_modulo text default null,
  p_accion text default null,
  p_entidad_tipo text default null,
  p_busqueda text default null,
  p_limite integer default 200,
  p_offset integer default 0
)
returns table (
  id bigint,
  comercio_id uuid,
  modulo text,
  accion text,
  entidad_tipo text,
  entidad_id text,
  referencia text,
  detalle jsonb,
  realizado_por uuid,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $function$
declare
  v_limite integer;
  v_offset integer;

  v_busqueda text;
begin

  perform public.exigir_permiso_comercio(
    p_comercio_id,
    'auditoria.ver'
  );


  v_limite :=
    least(
      greatest(coalesce(p_limite, 200), 1),
      1000
    );


  v_offset :=
    greatest(
      coalesce(p_offset, 0),
      0
    );


  v_busqueda :=
    nullif(
      trim(coalesce(p_busqueda, '')),
      ''
    );


  return query
  select
    ao.id,
    ao.comercio_id,
    ao.modulo,
    ao.accion,
    ao.entidad_tipo,
    ao.entidad_id,
    ao.referencia,
    ao.detalle,
    ao.realizado_por,
    ao.created_at
  from public.auditoria_operaciones ao
  where ao.comercio_id = p_comercio_id

    and (
      p_fecha_desde is null
      or ao.created_at >= p_fecha_desde::timestamptz
    )

    and (
      p_fecha_hasta is null
      or ao.created_at
        < (p_fecha_hasta + 1)::timestamptz
    )

    and (
      nullif(trim(coalesce(p_modulo, '')), '') is null
      or ao.modulo = trim(p_modulo)
    )

    and (
      nullif(trim(coalesce(p_accion, '')), '') is null
      or ao.accion = trim(p_accion)
    )

    and (
      nullif(trim(coalesce(p_entidad_tipo, '')), '') is null
      or ao.entidad_tipo = trim(p_entidad_tipo)
    )

    and (
      v_busqueda is null

      or ao.referencia ilike '%' || v_busqueda || '%'

      or ao.entidad_id ilike '%' || v_busqueda || '%'

      or ao.modulo ilike '%' || v_busqueda || '%'

      or ao.accion ilike '%' || v_busqueda || '%'

      or ao.entidad_tipo ilike '%' || v_busqueda || '%'

      or ao.detalle::text ilike '%' || v_busqueda || '%'
    )

  order by ao.created_at desc, ao.id desc

  limit v_limite
  offset v_offset;

end;
$function$;


revoke all on function
public.obtener_auditoria_operaciones(
  uuid,
  date,
  date,
  text,
  text,
  text,
  text,
  integer,
  integer
)
from public, anon;


grant execute on function
public.obtener_auditoria_operaciones(
  uuid,
  date,
  date,
  text,
  text,
  text,
  text,
  integer,
  integer
)
to authenticated;


-- ============================================================
-- 7. VERIFICACIÓN ESTRUCTURAL
-- ============================================================

select jsonb_build_object(

  'tabla',
    to_regclass(
      'public.auditoria_operaciones'
    ) is not null,

  'permiso_auditoria_ver',
    exists (
      select 1
      from public.permisos_sistema ps
      where ps.codigo = 'auditoria.ver'
        and ps.activo = true
    ),

  'admin_con_permiso',
    exists (
      select 1
      from public.roles_permisos rp
      where rp.rol = 'admin'
        and rp.permiso_codigo = 'auditoria.ver'
        and rp.permitido = true
    ),

  'helper_interno',
    to_regprocedure(
      'public.__drito_registrar_auditoria_operacion(uuid,text,text,text,text,text,jsonb,uuid)'
    ) is not null,

  'rpc_consulta',
    to_regprocedure(
      'public.obtener_auditoria_operaciones(uuid,date,date,text,text,text,text,integer,integer)'
    ) is not null,

  'rls_activo',
    (
      select c.relrowsecurity
      from pg_class c
      join pg_namespace n
        on n.oid = c.relnamespace
      where n.nspname = 'public'
        and c.relname = 'auditoria_operaciones'
    ),

  'authenticated_insert_directo',
    has_table_privilege(
      'authenticated',
      'public.auditoria_operaciones',
      'INSERT'
    ),

  'authenticated_update_directo',
    has_table_privilege(
      'authenticated',
      'public.auditoria_operaciones',
      'UPDATE'
    ),

  'authenticated_delete_directo',
    has_table_privilege(
      'authenticated',
      'public.auditoria_operaciones',
      'DELETE'
    ),

  'registros_iniciales',
    (
      select count(*)
      from public.auditoria_operaciones
    )

) as verificacion_15a2;